// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemperatureUnit } from "./TemperatureUnit";

export type ApplicationPreferenceChange = { "type": "set_temperature_unit", value: TemperatureUnit, } | { "type": "set_telemetry_interval_ms", value: bigint, } | { "type": "set_launch_at_login", value: boolean, };
