// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BatteryReading = { charge_percent: number, temperature_celsius: number | null, is_charging: boolean, cycle_count: number | null, power_watts: number | null, };
