// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FanTarget } from "./FanTarget";

export type FanPlan = { "type": "system_auto" } | { "type": "targets", targets: Array<FanTarget>, };
