// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FanMode } from "./FanMode";

export type FanReading = { id: number, label: string, speed_rpm: number, min_speed_rpm: number, max_speed_rpm: number, target_speed_rpm: number | null, mode: FanMode, };
