// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Availability } from "./Availability";
import type { BatteryReading } from "./BatteryReading";
import type { FanActuationStatus } from "./FanActuationStatus";
import type { FanReading } from "./FanReading";
import type { TemperatureReadings } from "./TemperatureReadings";

export type HardwareTelemetrySnapshot = { temperatures: Availability<TemperatureReadings>, fans: Availability<Array<FanReading>>, battery: Availability<BatteryReading>, fan_actuation_status: FanActuationStatus, captured_at_unix_ms: number, };
