// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThermalPolicyMode } from "./ThermalPolicyMode";
import type { ThermalRule } from "./ThermalRule";

export type ThermalPolicySettings = { mode: ThermalPolicyMode, rules: Array<ThermalRule>, };
